# Generated by Django 5.0.4 on 2024-04-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_title", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("publisher", models.CharField(blank=True, max_length=100)),
                ("summary", models.TextField()),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Does this reivew allow public?",
                        verbose_name="is Public?",
                    ),
                ),
            ],
        ),
    ]
