# Generated by Django 5.0.4 on 2024-04-27 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="owner",
            new_name="user",
        ),
    ]
