# Generated by Django 5.0.4 on 2024-05-10 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_alter_book_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="rating",
            field=models.PositiveIntegerField(
                null=True, validators=[django.core.validators.MaxValueValidator(5)]
            ),
        ),
    ]
