# Generated by Django 5.0.4 on 2024-05-10 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_book_rating"),
        ("gptCreate", "0001_initial"),
        ("movies", "0003_alter_movie_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gptphoto",
            name="author",
        ),
        migrations.RemoveField(
            model_name="gptphoto",
            name="content",
        ),
        migrations.RemoveField(
            model_name="gptphoto",
            name="publisher",
        ),
        migrations.RemoveField(
            model_name="gptphoto",
            name="title",
        ),
        migrations.RemoveField(
            model_name="gptphoto",
            name="user",
        ),
        migrations.AlterField(
            model_name="gptphoto",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gptPhotos",
                to="books.book",
            ),
        ),
        migrations.AlterField(
            model_name="gptphoto",
            name="movie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gptPhotos",
                to="movies.movie",
            ),
        ),
    ]
