# Generated by Django 5.0.4 on 2024-05-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gptCreate", "0002_remove_gptphoto_author_remove_gptphoto_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gptphoto",
            name="file",
            field=models.TextField(),
        ),
    ]
