# Generated by Django 5.0.4 on 2024-05-16 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_book_rating"),
        ("gptCreate", "0003_alter_gptphoto_file"),
        ("movies", "0003_alter_movie_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gptphoto",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gptphotos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="gptphoto",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gptphotos",
                to="books.book",
            ),
        ),
        migrations.AlterField(
            model_name="gptphoto",
            name="movie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gptphotos",
                to="movies.movie",
            ),
        ),
    ]
