# Generated by Django 5.0.4 on 2024-04-29 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_alter_book_user"),
        ("liked", "0003_initial"),
        ("movies", "0004_alter_movie_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="liked",
            name="books",
        ),
        migrations.RemoveField(
            model_name="liked",
            name="movies",
        ),
        migrations.AddField(
            model_name="liked",
            name="books",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked",
                to="books.book",
            ),
        ),
        migrations.AddField(
            model_name="liked",
            name="movies",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked",
                to="movies.movie",
            ),
        ),
    ]
