# Generated by Django 5.0.4 on 2024-04-29 16:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("liked", "0005_remove_liked_name_liked_payload"),
    ]

    operations = [
        migrations.RenameField(
            model_name="liked",
            old_name="books",
            new_name="book",
        ),
        migrations.RenameField(
            model_name="liked",
            old_name="movies",
            new_name="movie",
        ),
    ]
