# Generated by Django 5.0.4 on 2024-05-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medias", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="description",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
