# Generated by Django 5.0.4 on 2024-04-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("review_title", models.CharField(max_length=100)),
                ("director", models.CharField(blank=True, max_length=100)),
                ("cast", models.CharField(blank=True, max_length=200)),
                ("content", models.TextField()),
                ("summary", models.TextField()),
            ],
        ),
    ]
