# Generated by Django 5.0.4 on 2024-04-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="Does this reivew allow public?",
                verbose_name="is Public?",
            ),
        ),
    ]
